// react-app/src/components/animal-form/animal-form.jsx
function AnimalForm({showForm, animal, handle, handleSubmit, onFileChanged}) {
    return (
        <div className="animal-form">
            <div className="animal-form__wrap">
                <div className="animal-form__panel">
                    <div onClick={showForm} className="animal-form__close">×
                    </div>
                    <div className="animal-form__title">Добавить животного</div>
                    <form onSubmit={handleSubmit} className="form">
                        <div className="form__group">
                            <label htmlFor="type">Тип животного *</label>
                            <input
                                onChange={(e => handle(e))}
                                className="form__control"
                                id="type"
                                value={animal.type}
                                maxLength="20"
                                minLength="3" name="type"
                                pattern="^[A-Za-zА-Яа-яЁё]+$"
                                required type="text"/>
                        </div>
                        <div className="form__group">
                            <label htmlFor="name">Имя *</label>
                            <input
                                onChange={(e => handle(e))}
                                className=" form__control"
                                id="name"
                                value={animal.name}
                                maxLength="20"
                                minLength="3"
                                name="name"
                                pattern="^[A-Za-zА-Яа-яЁё]+$"
                                required
                                type="text"/>
                        </div>

                        <div className="form__group">
                            <label htmlFor="breed">Порода *</label>
                            <input
                                onChange={(e => handle(e))}
                                className="form__control"
                                id="breed"
                                value={animal.breed}
                                maxLength="20"
                                minLength="3"
                                name="breed" pattern="^[A-Za-zА-Яа-яЁё]+$"
                                required
                                type="text"/>
                        </div>

                        <div className="form__group">
                            <label htmlFor="gender">Пол *</label>
                            <select
                                onChange={(e => handle(e))}
                                className="form__control" id="gender"
                                name="gender"
                                value={animal.gender}
                                required>
                                <option value="М">М</option>
                                <option value="Ж">Ж</option>
                            </select>
                        </div>
                        <div className="form__group">
                            <label htmlFor="age">Возраст</label>
                            <input
                                onChange={(e => handle(e))}
                                className="form__control"
                                id="age"
                                value={animal.age}
                                name="age" pattern="[0-9]{1,2}" type="text"/>
                        </div>
                        <div className="form__group">
                            <label htmlFor="weight">Вес (г.)</label>
                            <input
                                onChange={(e => handle(e))}
                                className="form__control"
                                id="weight"
                                value={animal.weight}
                                name="weight" pattern="^[0-9]+$" type="text"/>
                        </div>
                        <div className="form__group">
                            <label htmlFor="furLength">Шерсть</label>
                            <input
                                onChange={(e => handle(e))}
                                className="form__control" id="furLength"
                                value={animal.furLength}
                                name="furLength" type="text"/>
                        </div>
                        <div className="form__group">
                            <label htmlFor="img">Изображение *</label>
                            <input
                                onChange={(e => onFileChanged(e))}
                                className="form__control"
                                id="img"
                                name="img" type="file"/>
                        </div>
                        <div className="form__group">
                            <button className="form__btn"
                                    type="submit">Отправить
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>)
}

export default AnimalForm;

// AngularTask16/src/animals/animal-form/animal-form.component.ts
import {Component, EventEmitter, OnInit, Output} from '@angular/core';
import {Animal, DataService} from "../services/data.service";
import {NgForm} from "@angular/forms";
import {Store} from "@ngrx/store";
import {AddAnimalAction} from "../store/data.actions";

@Component({
  selector: 'app-animal-form',
  templateUrl: './animal-form.component.html',
  styleUrls: ['./animal-form.component.less']
})
export class AnimalFormComponent implements OnInit {
  public _animal: Animal = {breed: '', name: '', type: '', gender: '', age: 0, weight: 0, furLength: '', img: ''};

  @Output() isConfirmed: EventEmitter<boolean> = new EventEmitter<boolean>();

  constructor(private store$: Store<Animal>, private _dataService: DataService) {
  }

  public _closeForm() {
    this.isConfirmed.emit(false);
  }

  public _onFileChanged(e: any) {
    if (e.target.files) {
      const reader = new FileReader();
      reader.readAsDataURL(e.target.files[0]);
      reader.onload = (event: any) => {
        this._animal.img = event.target.result;
      }

    }
  }

  ngOnInit(): void {
  }

  public _onSubmit(form: NgForm) {
    if (form.valid) {
      let animal: Animal = this._animal;
      this.store$.dispatch(new AddAnimalAction({animal}))
    }
  }
}

<div class="animal-form">
  <div class="animal-form__wrap">
    <div class="animal-form__panel">
      <div (click)="_closeForm()" class="animal-form__close">×</div>
      <div class="animal-form__title">Добавить животного</div>
      <form #templateForm="ngForm" (ngSubmit)="_onSubmit(templateForm)" class="form">
        <div class="form__group">
          <label for="type">Тип животного *</label>
          <input #type="ngModel" [(ngModel)]="_animal.type"
                 [ngClass]="{'is-invalid': type.invalid && type.touched, 'is-valid': type.dirty && type.valid}"
                 class="form__control"
                 id="type"
                 maxlength="15"
                 minlength="3" name="type"
                 pattern="^[A-Za-zА-Яа-яЁё]+$"
                 required type="text">
        </div>
        <div class="form__group">
          <label for="name">Имя *</label>
          <input #name="ngModel" [(ngModel)]="_animal.name"
                 [ngClass]="{'is-invalid': name.invalid && name.touched, 'is-valid': name.dirty && name.valid}"
                 class="form__control"
                 id="name"
                 maxlength="15"
                 minlength="3"
                 name="name"
                 pattern="^[A-Za-zА-Яа-яЁё]+$"
                 required
                 type="text">
        </div>

        <div class="form__group">
          <label for="breed">Порода *</label>
          <input #breed="ngModel" [(ngModel)]="_animal.breed"
                 [ngClass]="{'is-invalid': breed.invalid && breed.touched, 'is-valid': breed.dirty && breed.valid}"
                 class="form__control"
                 id="breed"
                 maxlength="15"
                 minlength="3"
                 name="breed" pattern="^[A-Za-zА-Яа-яЁё]+$"
                 required
                 type="text">
        </div>

        <div class="form__group">
          <label for="gender">Пол *</label>
          <select #gender="ngModel" [(ngModel)]="_animal.gender"
                  [ngClass]="{'is-invalid' : gender.pristine && gender.touched, 'is-valid': gender.dirty && gender.valid}"
                  class="form__control" id="gender"
                  name="gender"
                  required>
            <option value="М">М</option>
            <option value="Ж">Ж</option>
          </select>
        </div>
        <div class="form__group">
          <label for="age">Возраст</label>
          <input #age="ngModel" [(ngModel)]="_animal.age"
                 [ngClass]="{'is-invalid': age.invalid && age.touched, 'is-valid': age.dirty && age.valid}"
                 class="form__control"
                 id="age"
                 name="age" pattern="[0-9]{1,2}" type="text">
        </div>
        <div class="form__group">
          <label for="weight">Вес (г.)</label>
          <input [(ngModel)]="_animal.weight" class="form__control" id="weight"
                 name="weight" pattern="^[0-9]+$" type="text">
        </div>
        <div class="form__group">
          <label for="furLength">Шерсть</label>
          <input [(ngModel)]="_animal.furLength" class="form__control" id="furLength"
                 name="furLength" type="text">
        </div>
        <div class="form__group">
          <label for="img">Изображение</label>
          <input (change)="_onFileChanged($event)" class="form__control"
                 id="img" name="img" required type="file">
        </div>
        <div class="form__group">
          <button [disabled]="templateForm.invalid" class="form__btn"
                  type="submit">Отправить
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
