// react-app/src/components/animal-edit/animal-edit.jsx
import './animal-edit.css';
import {NavLink} from "react-router-dom";
import React from "react";


function AnimalEdit({animal, handle, handleSubmit, onFileChanged}) {
    return (
        <div className="animal-form">
            <div className="animal-form__wrap">
                <div className="animal-form__panel">
                    <NavLink to="/">
                        <div className="animal-form__close">×</div>
                    </NavLink>

                    <div className="animal-form__title">Редактировать животного</div>
                    <form className="form" onSubmit={handleSubmit}>
                        <div className="form__group">
                            <label>Тип животного</label>
                            <input onChange={(e => handle(e))} value={animal.type} className="form__control"
                                   name="type"/>
                        </div>
                        <div className="form__group">
                            <label>Имя</label>
                            <input onChange={(e => handle(e))} id="name" value={animal.name} className="form__control"
                                   name="name"/>
                        </div>
                        <div className="form__group">
                            <label>Порода</label>
                            <input onChange={(e => handle(e))} value={animal.breed} className="form__control"
                                   name="breed"/>
                        </div>
                        <div className="form__group">
                            <label>Пол</label>
                            <select onChange={(e => handle(e))} value={animal.gender} className="form__control"
                                    name="gender">
                                <option value="М">М</option>
                                <option value="Ж">Ж</option>
                            </select>
                        </div>
                        <div className="form__group">
                            <label>Возраст</label>
                            <input onChange={(e => handle(e))} value={animal.age} className="form__control" name="age"/>
                        </div>
                        <div className="form__group">
                            <label htmlFor="weight">Вес (г.)</label>
                            <input onChange={(e => handle(e))} value={animal.weight} className="form__control"
                                   id="weight" name="weight"/>
                        </div>
                        <div className="form__group">
                            <label htmlFor="furLength">Шерсть</label>
                            <input onChange={(e => handle(e))} value={animal.furLength} className="form__control"
                                   id="furLength" name="furLength" type="text"/>
                        </div>
                        <div className="form__group">
                            <label htmlFor="img">Изображение</label>
                            <input onChange={(e => onFileChanged(e))} className="form__control"
                                   id="img" name="img" type="file"/>
                        </div>
                        <div className="form__group">
                            <button className="form__btn" type="submit">
                                Отправить
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    )
}

export default AnimalEdit;

// AngularTask16/src/animals/animal-edit/animal-edit.component.ts
import {Component, OnInit} from '@angular/core';
import {ActivatedRoute} from "@angular/router";
import {switchMap} from "rxjs/operators";
import {FormControl, FormGroup, Validators} from "@angular/forms";
import {Animal, DataService} from "../services/data.service"
import {Store} from "@ngrx/store";
import {GetAnimalAction, UpdateAnimalAction} from "../store/data.actions";
import {selectAnimal} from "../store/data.selectors";


@Component({
  selector: 'app-animal-edit',
  templateUrl: './animal-edit.component.html',
  styleUrls: ['./animal-edit.component.less']
})
export class AnimalEditComponent implements OnInit {
  public _reactiveForm: FormGroup;
  private _animal: Animal = {breed: '', name: '', type: '', gender: '', age: 0, weight: 0, furLength: '', img: ''}

  constructor(private store$: Store<Animal>, private _dataService: DataService, private _route: ActivatedRoute) {
    this._reactiveForm = new FormGroup({
      "type": new FormControl('', [
        Validators.pattern("^[A-Za-zА-Яа-яЁё]+$"),
        Validators.maxLength(15),
        Validators.minLength(3)
      ]),
      "name": new FormControl('', [
        Validators.pattern("^[A-Za-zА-Яа-яЁё]+$"),
        Validators.maxLength(15),
        Validators.minLength(3)
      ]),
      "breed": new FormControl('', [
        Validators.pattern("^[A-Za-zА-Яа-яЁё]+$"),
        Validators.maxLength(15),
        Validators.minLength(3)
      ]),
      "gender": new FormControl(''),
      "age": new FormControl('', Validators.pattern("[0-9]{1,2}")),
      "weight": new FormControl('', Validators.pattern("^[0-9]+$")),
      "furLength": new FormControl(''),
      "img": new FormControl('')
    });
  }


  ngOnInit() {
    this._route.paramMap.pipe(
      switchMap(params => params.getAll('id'))).subscribe(id => {
      this.store$.dispatch(new GetAnimalAction({id}))
      this.store$.select(selectAnimal).subscribe(animal => {
        this._animal = Object.assign({}, animal)
        this._initForm()
      });

    });

  }

  public _onFileChanged(e: any) {
    if (e.target.files) {
      const reader = new FileReader();
      reader.readAsDataURL(e.target.files[0]);
      reader.onload = (event: any) => {
        this._animal.img = event.target.result;
      }
    }
  }

  public _onSubmit() {
    if (this._reactiveForm.valid) {
      this._prepareSaveAnimal();
      const animal: Animal = Object.assign({}, this._animal)
      this.store$.dispatch(new UpdateAnimalAction({animal}))
    }
  }

  private _initForm() {
    this._reactiveForm.patchValue({
      type: this._animal.type,
      name: this._animal.name,
      breed: this._animal.breed,
      gender: this._animal.gender,
      age: this._animal.age,
      weight: this._animal.weight,
      furLength: this._animal.furLength,
    });

  }

  private _prepareSaveAnimal(): void {
    const formModel = this._reactiveForm.value;
    this._animal.type = formModel.type;
    this._animal.name = formModel.name;
    this._animal.breed = formModel.breed;
    this._animal.gender = formModel.gender;
    this._animal.age = formModel.age;
    this._animal.weight = formModel.weight;
    this._animal.furLength = formModel.furLength;
  }
}

<div class="animal-form">
  <div class="animal-form__wrap">
    <div class="animal-form__panel">
      <div class="animal-form__close" routerLink="">×</div>
      <div class="animal-form__title">Редактировать животного</div>
      <form (ngSubmit)="_onSubmit()" [formGroup]="_reactiveForm" class="form">
        <div class="form__group">
          <label>Тип животного</label>
          <input
            [ngClass]="{'is-invalid': _reactiveForm.controls['type'].invalid && _reactiveForm.controls['type'].touched, 'is-valid': _reactiveForm.controls['type'].dirty && _reactiveForm.controls['type'].valid}"
            class="form__control" formControlName="type" name="type"/>
        </div>
        <div class="form__group">
          <label>Имя</label>
          <input
            [ngClass]="{'is-invalid': _reactiveForm.controls['name'].invalid && _reactiveForm.controls['name'].touched, 'is-valid': _reactiveForm.controls['name'].dirty && _reactiveForm.controls['name'].valid}"
            class="form__control" formControlName="name" name="name"/>
        </div>
        <div class="form__group">
          <label>Порода</label>
          <input
            [ngClass]="{'is-invalid': _reactiveForm.controls['breed'].invalid && _reactiveForm.controls['breed'].touched, 'is-valid': _reactiveForm.controls['breed'].dirty && _reactiveForm.controls['breed'].valid}"
            class="form__control" formControlName="breed" name="breed"/>
        </div>
        <div class="form__group">
          <label>Пол</label>
          <select
            [ngClass]="{'is-invalid' : _reactiveForm.controls['gender'].pristine && _reactiveForm.controls['gender'].touched, 'is-valid': _reactiveForm.controls['gender'].dirty && _reactiveForm.controls['gender'].valid}"
            class="form__control" formControlName="gender"
            name="gender">
            <option value="М">М</option>
            <option value="Ж">Ж</option>
          </select>
        </div>
        <div class="form__group">
          <label>Возраст</label>
          <input
            [ngClass]="{'is-invalid': _reactiveForm.controls['age'].invalid && _reactiveForm.controls['age'].touched, 'is-valid': _reactiveForm.controls['age'].dirty && _reactiveForm.controls['age'].valid}"
            class="form__control" formControlName="age" name="age"/>
        </div>
        <div class="form__group">
          <label for="weight">Вес (г.)</label>
          <input class="form__control"
                 formControlName="weight" id="weight" name="weight"/>
        </div>
        <div class="form__group">
          <label for="furLength">Шерсть</label>
          <input class="form__control" formControlName="furLength"
                 id="furLength" name="furLength" type="text">
        </div>
        <div class="form__group">
          <label for="img">Изображение</label>
          <input (change)="_onFileChanged($event)"
                 class="form__control" formControlName="img"
                 id="img" name="img" type="file">
        </div>
        <div class="form__group">
          <button [disabled]="_reactiveForm.invalid" class="form__btn" type="submit">
            Отправить
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
